.github/workflows/deploy-gh-pages.yml, next.config.ts
=> fix builds

app/components/Home.tsx, app/globals.css, package.json
=> fix navbar spaces 

app/components/Challenges.tsx, app/components/Context.tsx, app/components/Footer.tsx, app/components/Header.tsx, app/components/Hero.tsx, app/components/Impact.tsx, app/components/Participation.tsx, app/components/Solutions.tsx, app/components/Timeline.tsx, app/mockups/page.tsx, app/page.tsx
=> landing page

.github/workflows/deploy-gh-pages.yml, app/components/Challenges.tsx, app/components/Footer.tsx, app/components/Hero.tsx, app/components/Impact.tsx, app/components/Solutions.tsx
=> fix challenges section

app/components/Challenges.tsx, app/components/Context.tsx, app/components/Footer.tsx
=> fix footer logos

app/components/Home.tsx, app/components/Landing.tsx, app/components/ToolDetailModel.tsx, app/components/categories-drawer.tsx, app/hooks/use-mobile.tsx, components/ui/sheet.tsx
=> fix responsiveness tablet and mobile

app/api/support/route.ts
=> fix resend email sending

app/components/FilterDrawer.tsx, app/components/Home.tsx, app/components/categories-drawer.tsx, app/layout.tsx, app/types/index.ts
=> fix layout designs and tools chips

app/components/Home.tsx, app/components/categories-drawer.tsx, app/components/suggestion-banner.tsx
=> feat add banner on mobile and desktop

app/components/support-bubble/bubble.tsx, app/components/support-bubble/support-form.tsx
=> fix supporting form

app/components/Home.tsx, app/components/Landing.tsx, app/components/Questionairefilter.tsx, app/utils/questionnaire-utils.ts
=> added filters after question completion

app/components/Questionairefilter.tsx
=> fix tool finder length recommendations

app/components/ToolDetailModel.tsx
=> add report mistake link on tool overview

app/components/Home.tsx, app/components/ToolDetailModel.tsx, app/components/categories-drawer.tsx, app/components/suggestion-banner.tsx, app/components/support-bubble-provider.tsx, app/components/support-bubble/mini-bubble.tsx, public/tools/Learn.ink.yaml, public/tools/odoo.yaml, public/tools/odyssey-fern.yaml, public/tools/paygops.yaml, public/tools/vida.yaml
=> fix Latest feedback - 03.07.2025

app/components/Home.tsx, app/components/Questionairefilter.tsx, app/utils/filterTools.ts
=> fix toools recommendations length

app/components/Home.tsx, app/components/Landing.tsx
=> fix not found tools message

app/components/Questionairefilter.tsx, app/components/ToolDetailModel.tsx, app/components/suggestion-banner.tsx
=> fix:suggestions texts and colors

app/components/Home.tsx
=> fix no tools found to remove few filters

app/components/Home.tsx, app/components/support-bubble-provider.tsx, app/components/support-bubble/mini-bubble.tsx
=> feat:mini bubble

app/layout.tsx
=> change meta name
